### ISSUE TITLE
Feautures not working

### ISSUE THREAD

**Issue by iamworldian** [mrinc/Facebook-Hide-Recommendations-and-Reels#17]
I have installed the extension recently.But seems like it's not working.Not sure why.

**Comment by mrinc** [comment]
Try the latest and see if it works: https://github.com/mrinc/Facebook-Hide-Recommendations-and-Reels/releases/tag/v1.21.3 

Note the langs supported: https://github.com/mrinc/Facebook-Hide-Recommendations-and-Reels/blob/v1.21.3/src/content/langs.ts
