### ISSUE TITLE
Firefox?

### ISSUE THREAD

**Issue by neuhaus** [mrinc/Facebook-Hide-Recommendations-and-Reels#2]
This only works with Chrome, right? What would it take to add Firefox support?

**Comment by mrinc** [comment]
We've pushed some changes and pushed the extension to the firefox store :)   
Just waiting on validation

**Comment by mrinc** [comment]
https://addons.mozilla.org/en-US/firefox/addon/fb-hide-recomm-and-reels/

It's live @neuhaus

**Comment by neuhaus** [comment]
Awesome, that was fast!
