### ISSUE TITLE
for japanese

### ISSUE THREAD

**Issue by warpkwd** [mrinc/Facebook-Hide-Recommendations-and-Reels#21]
ja: {
    // Japanese
    newsFeedPosts: "News Feed posts",
    reelsBlock: "リールとショート動画",
    commentedOn: " commented on a post from ",
    peopleKnow: "People You May Know",
    suggested: ">Suggested for you<",
  },

**Comment by mrinc** [comment]
v1.21.3

**Comment by warpkwd** [comment]
Thank you.
But it did not work only this apply.
Reels line does not disapplear.

**Comment by mrinc** [comment]
@warpkwd `v1.25.3` will fix this :)
