### ISSUE TITLE
Is it possible to add the dutch language (nl)

### ISSUE THREAD

**Issue by jerre213** [mrinc/Facebook-Hide-Recommendations-and-Reels#23]
I would like to use this extension on my dutch language feed (nl) or (nl-be) if that exists.
Translations:
- Reels: "Reels and korte video's"

**Comment by mrinc** [comment]
Hey

Ref: https://github.com/mrinc/Facebook-Hide-Recommendations-and-Reels/blob/master/src/content/langs.ts 

We need the following info and then we can add it :) 

```
en: {
    // English
    newsFeedPosts: "News Feed posts",
    reelsBlock: "Reels and short videos",
    commentedOn: " commented on a post from ",
    peopleKnow: "People You May Know",
    suggested: ">Suggested for you<",
    answeredQuestion: " answered this question."
  },
```

**Comment by jerre213** [comment]
Hi mrinc,
I have scrolled a lot through my fb feed to try to find the translations. I did not encounter all of them though.
What type of content is "News Feed posts" and  " answered this question."?
CommentedOn I sometimes see but not at this time when I'm looking for it 😄 
I'm also not sure if I should add the >< characters in the suggested item.

Would it be possible to already add my language based on the current input and adapt later if I find more categories?

```
nl: {
    // Nederlands
    newsFeedPosts: "News Feed posts",
    reelsBlock: "Reels and korte video's",
    commentedOn: " commented on a post from ",
    peopleKnow: "Mensen die je misschien kent",
    suggested: ">Aanbevolen voor jou<",
    answeredQuestion: " answered this question."
  },
```

**Comment by mrinc** [comment]
Unfortunately we need to match all otherwise we'd have to rewrite the code to handle partial langs.  

So a direct translation would suffice but if you see something that doesn't match, you or anyone can log an issue and we can update it accordingly later on.

The keys are there for matching, can probs move them into the code instead to make langs simpler.

```
nl: {
    // Dutch
    newsFeedPosts: "Berichten in het nieuwsoverzicht",
    reelsBlock: "Reels and korte video's",
    commentedOn: " reageerde op een bericht van ",
    peopleKnow: "Mensen die je misschien kent",
    suggested: ">Aanbevolen voor jou<",
    answeredQuestion: " beantwoordde deze vraag."
  },
```

That good?

**Comment by mrinc** [comment]
Next release it will have it - v1.25.0

**Comment by jerre213** [comment]
thank you! I feel liberated already 😄
