### ISSUE TITLE
Current version on Chrome Web Store is no longer working (v1.18)

### ISSUE THREAD

**Issue by Bumboria** [mrinc/Facebook-Hide-Recommendations-and-Reels#5]
Hello,

I would like to inform that the current version on Chrome (1.18) is no longer hiding suggested or sponsored posts. I've tried installing the v1.19 provided on your GitHub but got stuck with "manifest not readable" or "name is missing or invalid"

**Comment by mrinc** [comment]
`v1.19.2` Just got published on the Chrome store.  
But I see the issue and it's still affecting v19.   

Will push a new version shortly for chrome :)

**Comment by mrinc** [comment]
Fixed in latest commit - https://github.com/mrinc/Facebook-Hide-Recommendations-and-Reels/commit/c3999547937e7ca65b3a7cb77d694574b2f8a36d

**Comment by mrinc** [comment]
Thanks @Bumboria for reporting this.  

Looks like Google and firefox have released the update already and it seems to have resolved the issues.

**Comment by Bumboria** [comment]
Confirm that it's working as intended now. Thank you for updating!
