### ISSUE TITLE
Polish laguage support

### ISSUE THREAD

**Issue by Marx2** [mrinc/Facebook-Hide-Recommendations-and-Reels#6]
Doesn't work in polish language
Sponsored section is marked with: "Sponsorowane"
Reels: "Rolki i krótkie filmy"
Suggestions: "Proponowana dla Ciebie"

Edit: I see that you store config booleans. Maybe the easiest would be to allow user set in config those strings to any value. That way your extension would support any language

**Comment by mrinc** [comment]
I've added the ability for new langs - these are the things we need to know :)   
 -- https://github.com/mrinc/Facebook-Hide-Recommendations-and-Reels/blob/master/src/content.js#L1 
  
```  
newsFeedPosts: "News Feed posts",  
reelsBlock: "Reels and short videos",  
commentedOn: " commented on a post from ",  
peopleKnow: "People you may know",  
suggested: ">Suggested for you<"  
```  
  
Confirm this is correct for your lang?  

```  
newsFeedPosts: "Posty na kanale aktualności",  
reelsBlock: "Rolki i krótkie filmy",  
commentedOn: " skomentował post z ",  
peopleKnow: "Ludzie których możesz znać",  
suggested: ">Rolki i krótkie filmy<"  
```  

Unfortunately sponsored = ads ... and FB REALLY tries hard to stop the ads from being removed :(  
So we don't bother trying too clean them out... would have to make a full plugin just to get around their tricks haha

**Comment by Marx2** [comment]
Translation is corrected, thank you!
